name: base
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch::pytorch
  # - pytorch::torchvision
  # - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - conda-forge:cudnn
  - pytorch::torchtext
  # github runner doesn't have a gpu, it seems not working , disable for now. 
  # might work using https://github.com/gpgpu-sim/gpgpu-sim_distribution, check it later
  # - nvidia/label/cuda-11.8.0::cutatoolkit
  - pandas=2.0.3
  - pip
  - numpy=1.24.3
  - openpyxl=3.0.10
  - scipy=1.10.1
  - sqlalchemy=2.0.21
  - ipywidgets
  - ipympl
  - cython=0.29
  - statsmodels=0.14.0
  - notebook
  - loguru
  - jupyterlab
  - numba=0.58.1
  - numexpr=2.8.4
  - xlrd=2.0.1
  - conda-forge::torchinfo=1.8.0
  - conda-forge::imbalanced-learn=0.11.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::jupytext
  - conda-forge::spacy=3.5.4
  - conda-forge::pyarrow=14.0.1
  - pip:
    # https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/layers
    # may consider torchdynamo in later versions
    # https://pytorch.org/docs/stable/dynamo/installation.html
    - setuptools==65
    # tmp solution to fix the pip install medspacy     
    # - git+https://github.com/jianlins/medspacy.git
    - medspacy
    - git+https://github.com/medspacy/medspacy_io.git
    - transformers>=4.31.0
    # dependency version conflict, fix it later
    # - medpspacy-io
    - simpletransformers==0.64.5
    - nltk==3.8.1
    - bioc==2.0
    - tqdm==4.65
    - tensorboard
    - pytest
    - wheel
    - joblib
    - matplotlib
    - itsdangerous<2.1.0
    - accelerate
    - lightning==2.1.2
    - install-jdk    
    - pyspark[pandas_on_spark]==3.5.0
    - spark-nlp==5.2.0
    - gensim
    
