name: base
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch::pytorch
  # - pytorch::torchvision
  # - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - pytorch::faiss-gpu
  # https://docs.rapids.ai/install
  - rapidsai::rapids=23.04
  - pytorch::torchtext
  - pandas=2.0.2
  - numpy
  - openpyxl
  - scipy
  - sqlalchemy
  - ipywidgets
  - h5py
  - beautifulsoup4
  - bokeh
  - seaborn
  - ipympl
  - cython=0.29
  - statsmodels
  - notebook
  - jupyterlab
  - numba
  - numexpr
  - xlrd
  - conda-forge::torchinfo
  - conda-forge::imbalanced-learn
  - conda-forge::scikit-learn
  - conda-forge::jupytext
  - conda-forge::spacy=3.5
  - pip:
    # https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/layers
    - git+https://github.com/NVIDIA/TransformerEngine.git@release_v0.9
    - torch-tensorrt==1.4.0
    # may consider torchdynamo in later versions
    # https://pytorch.org/docs/stable/dynamo/installation.html
    - medspacy==1.1.2
    - medpspacy-io
    - simpletransformers==0.63
    - cupy-cuda11x
    - nltk==3.8.1
    - bioc==2.0
    - tqdm==4.65
    - tensorboard
    - pytest
    - setuptools
    - wheel
    - joblib
    - matplotlib
    - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.3.0/en_core_sci_sm-0.3.0.tar.gz
