name: vlinux_llama2
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch::pytorch
  # - pytorch::torchvision
  # - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - conda-forge:cudnn
  - pytorch::torchtext
  # github runner doesn't have a gpu, it seems not working , disable for now. 
  # might work using https://github.com/gpgpu-sim/gpgpu-sim_distribution, check it later
  # - nvidia/label/cuda-11.8.0::cutatoolkit
  - pandas=2.0.3
  - pip
  - numpy=1.24.3
  - openpyxl=3.0.10
  - scipy=1.10.1
  - sqlalchemy
  - ipywidgets
  - ipympl
  - cython=0.29
  - statsmodels=0.14.0
  - notebook
  - loguru
  - jupyterlab
  - numba=0.58.1
  - numexpr
  - xlrd
  - conda-forge::torchinfo=1.8.0
  - conda-forge::imbalanced-learn
  - conda-forge::scikit-learn
  - conda-forge::jupytext
  - conda-forge::spacy=3.5.4
  - conda-forge::pyarrow=14.0.1
  - pip:
    - setuptools==65
    - medspacy
    - git+https://github.com/medspacy/medspacy_io.git
    - transformers>=4.31.0
    - simpletransformers
    - nltk
    - bioc==2.0
    - tqdm
    - tensorboard
    - pytest
    - wheel
    - joblib
    - matplotlib
    - itsdangerous<2.1.0
    - accelerate
    - lightning
    - install-jdk    
    - pyspark==3.5.1
    - spark-nlp==5.3.3
    - spark-nlp-display
    - johnsnowlabs
    - gensim
    - tensorflow
    - tensorflow-text
    - wandb
    - grpcio
    - protobuf
    - grpcio-tools
    - googleapis-common-protos
    - ninja
    - pyyaml