name: base
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch::pytorch
  # - pytorch::torchvision
  # - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - conda-forge:cudnn
  - pytorch::torchtext
  # github runner doesn't have a gpu, it seems not working , disable for now. 
  # might work using https://github.com/gpgpu-sim/gpgpu-sim_distribution, check it later
  # - nvidia/label/cuda-11.8.0::cutatoolkit
  - pip
  - openpyxl=3.0.10
  - ipywidgets
  - ipympl
  - cython=0.29
  - notebook
  - jupyterlab
  - conda-forge::torchinfo=1.8.0
  - conda-forge::imbalanced-learn=0.11.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::jupytext
  - conda-forge::spacy=3.5.4
  - conda-forge::pyarrow=14.0.1
  - pip:
    - git+https://github.com/jianlins/medspacy.git
    - git+https://github.com/medspacy/medspacy_io.git
    - beautifulsoup4
    - bioc
    - simpletransformers
    - nltk
    - numba
    - numpy
    - sqlalchemy
    - ipympl
    - numexpr
    - statsmodels
    - bioc==2.0
    - tqdm
    - tensorboard
    - pytest
    - setuptools
    - wheel
    - scipy
    - joblib
    - qdrant-client
    - jupyterlab-widgets
    - matplotlib
    - itsdangerous
    - accelerate
    - lightning
    - loguru
    - findspark
    - install-jdk
    - tensorflow
    - pyspark==3.5.1
    - spark-nlp==5.2.3
    - gensim
    - python-dateutil
    - pyodbc
    - xgboost
    - xlrd
    - spark-nlp-display
    - openpyxl
    - git+https://github.com/facebookresearch/llama-recipes.git
    - git+https://github.com/facebookresearch/llama.git
    - findspark
    - flask
    - flask-restful
    - keras
    - lxml    
    - markdown
    - mlflow
    - multiprocess
    - murmurhash      
    - oauthlib
    - openpyxl    
    - optimum
    - pandas
    - preshed
    - protobuf
    - py4j
    - py7zr
    - pyarrow
    - pydantic
    - spacy==3.5.4
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - sqlalchemy
    - sqlparse
    - statsmodels
    - tensorflow
    - tokenizers
    - torchmetrics
    - unidecode
    - wandb
    - grpcio
    - protobuf
    - grpcio-tools
    - googleapis-common-protos
    - ninja
    - pyyaml
    - requests
    
