name: base
channels:
  - nvidia
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - nvidia/label/cuda-12.4.0::cuda
  - nvidia/label/cuda-12.4.0::cuda-nvcc
  - pandas=2.0.3
  - pip
  - numpy=1.24.3
  - sqlalchemy=2.0.21
  - ipympl
  - cython=0.29
  - loguru
  - jupyterlab
  - xlrd=2.0.1
  - pip:
    - setuptools==65
    - transformers>=4.31.0
    - tqdm==4.65
    - wheel
    - joblib
    - pyodbc
    - torchserve
    - torch-model-archiver
    - torch-workflow-archiver
    - requests
    - captum==0.6.0
    - packaging
    - pynvml
    - pyyaml
    - ninja
    # torchserve's client
    - grpcio
    - protobuf
    - grpcio-tools
    - googleapis-common-protos
    - flask
    - flask-restful
    - lmdeploy
    - sglang

