name: grounding-mwe
# Combined environment for omop-spires experiment_1_demo + vectordb test notebook
# Windows-friendly, air-gapped workflow capable.
channels:
  - conda-forge
  - nvidia
  - pytorch  
  - defaults
dependencies:
  - python=3.12
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=11.8
  - nvidia/label/cuda-11.8.0::cuda-nvcc
  - faiss-gpu
  - conda-forge:cudnn
  - pytorch::torchtext
  - numpy
  - openpyxl=3.0.10
  - sqlalchemy
  - ipympl
  - cython=0.29
  - loguru
  - jupyterlab
  - xlrd=2.0.1
  - conda-forge::torchinfo=1.8.0
  - conda-forge::imbalanced-learn=0.11.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::jupytext
  - conda-forge::spacy
  - conda-forge::pyarrow=14.0.1

  
  - pip
  # Consider adding 'uvicorn' or 'fastapi' via pip if you later run APIs.
  - pip:
      - setuptools
      - medspacy
      - git+https://github.com/medspacy/medspacy_io.git
      # Core earlier experiment dependencies
      - pandas==2.2.2
      - pydantic==2.11.7
      - instructor==1.10.0
      - openai==1.42.0
      - ontogpt==1.0.16
      - oaklib==0.6.23
      - python-dotenv==1.0.1
      - linkml-runtime==1.8.2
      - tqdm==4.66.5
      - requests==2.32.3
      - typing-extensions==4.12.2
      - pyspark==3.4.2

      # Vectordb / embedding notebook dependencies
      - pymilvus[model]==2.6.0        # Milvus client + model extra
      - langchain
      - langchain-community
      - langchain-milvus==0.2.1
      - langchain-openai==0.3.32
      - langchain-huggingface==0.3.1
      - langchain-elasticsearch
      - sentence-transformers==5.1.0  # heavy: pulls transformers, torch, etc.
      - ollama==0.5.3                 # local model mgmt integration

      # Image service / API components used in image-service-demo and wrappers
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - python-multipart==0.0.9      # enables FastAPI UploadFile form parsing
      - opencv-python-headless==4.10.0.84
      - elasticsearch
  

      # Optional earlier extras
      # - bertopic==0.17.3            # topic modeling (pulls sklearn, umap-learn, etc.)
    
          # If torch CPU wheels fail offline: pre-download from https://download.pytorch.org/whl/torch/ and add to wheels dir.

# -----------------------------------------------------------------------------
# OFFLINE EXTENSIONS
# New (relative to environment.experiment1.yml) you must pre-download: pymilvus, langchain-* packages,
# sentence-transformers, its transitive deps (torch, torchvision (maybe), transformers, tokenizers, huggingface-hub,
# safetensors, numpy, scikit-learn, scipy, threadpoolctl, joblib), and ollama. Also FastAPI/uvicorn,
# opencv-python-headless, python-multipart, and (optionally) jupyterlab/ipykernel.
# Suggested collection command (online machine):
#   pip download -r <(python scripts/export_requirements_full.py) -d wheels --python-version 3.12 --only-binary=:all:
# (Or manually list each package.)
# -----------------------------------------------------------------------------
