name: base
channels:
  - nvidia
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  # - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - nvidia/label/cuda-11.8.0::cuda-nvcc
  - faiss-gpu
  - conda-forge:cudnn
  - pytorch::torchtext
  # github runner doesn't have a gpu, it seems not working , disable for now. 
  # might work using https://github.com/gpgpu-sim/gpgpu-sim_distribution, check it later
  # - nvidia/label/cuda-11.8.0::cutatoolkit
  - pandas
  - pip
  - numpy
  - openpyxl=3.0.10
  - sqlalchemy
  - ipympl
  - cython=0.29
  - loguru
  - jupyterlab
  - xlrd=2.0.1
  - conda-forge::torchinfo=1.8.0
  - conda-forge::imbalanced-learn=0.11.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::jupytext
  - conda-forge::pyarrow=14.0.1
  - pip:
    # https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/layers
    # may consider torchdynamo in later versions
    # https://pytorch.org/docs/stable/dynamo/installation.html
    - setuptools
    - git+https://github.com/huggingface/transformers.git
    - flash-attn    
    # dependency version conflict, fix it later
    # - medpspacy-io
    - nltk==3.8.1
    - bioc==2.0
    - tqdm==4.65
    - tensorboard
    - pytest
    - wheel
    - joblib
    - accelerate
    - pyspark==3.4.2
    - spark-nlp==5.3.3
    - gensim
    - pyodbc
    - nvgpu
    - optimum
    - requests
    - packaging
    - pynvml
    - flask
    - flask-restful
    - ninja
    - torch-ort
    - onnxruntime-gpu
    - jupyterlab-freeze
    - scipy
    - sympy
    - statsmodels
