name: win_langchain
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - conda-forge::faiss-cpu
  - pip:
    # https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/layers
    # may consider torchdynamo in later versions
    # https://pytorch.org/docs/stable/dynamo/installation.html
    - setuptools==65
    - medspacy
    - nltk==3.8.1
    - bioc==2.0
    - beautifulsoup4
    - pytest
    - bioc
    - tqdm
    - pandas
    - loguru
    - matplotlib
    - install-jdk
    - gensim
    - xgboost
    - openpyxl
    - imbalanced-learn
    - scikit-learn
    - sklearn-crfsuite
    - scipy
    - pyodbc
    - cython==0.29
    - sqlalchemy
    - xlrd
    - ipympl
    - ipywidgets
    - jupytext
    - lxml
    - markdown
    - jupyterlab-widgets
    - wheel
    - joblib
    - itsdangerous<2.1.0
    - accelerate
    - pyspark==3.4.2
    - spark-nlp==5.3.3  
    - pyarrow
    - findspark
    - spark-nlp-display
    - dspy-ai==2.4.0
    - datasets
    - py7zr
    - langchain
    - langchain-core
    - langchain-community
    - langchain-experimental
    - langgraph
    - langchain-cli
    - langsmith
    - langchain-openai
    - langchain-huggingface
    - langchain-anthropic

