name: win_langchain
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - conda-forge::faiss-cpu
  - pip:
    - pyspark==3.4.2
    - spark-nlp==5.3.3  
    - pyarrow
    - findspark
    - spark-nlp-display
    

