name: base
channels:
  - nvidia
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=11.8
  - nvidia/label/cuda-11.8.0::cuda-nvcc
  - faiss-gpu
  - conda-forge:cudnn
  - pytorch::torchtext
  - pandas
  - pip
  - numpy
  - openpyxl=3.0.10
  - sqlalchemy
  - ipympl
  - cython=0.29
  - loguru
  - jupyterlab
  - xlrd=2.0.1
  - conda-forge::torchinfo=1.8.0
  - conda-forge::imbalanced-learn=0.11.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::jupytext
  - conda-forge::spacy=3.5.4
  - conda-forge::pyarrow=14.0.1
  - cmake  
  - pip:
    - setuptools==65
    - medspacy
    - git+https://github.com/medspacy/medspacy_io.git
    - transformers>=4.31.0
    - simpletransformers
    - gpt4all
    - bitsandbytes
    - xformers
    - auto-gptq
    - nltk==3.8.1
    - bioc==2.0
    - tqdm==4.65
    - tensorboard
    - tensorrt==8.6.1
    - pytest
    - wheel
    - joblib
    - itsdangerous<2.1.0
    - accelerate
    - lightning==2.1.2
    - pyspark==3.4.2
    - spark-nlp==5.3.3
    - gensim
    - git+https://github.com/HarryCaveMan/sklearn-crfsuite.git
    - pyodbc
    - torchserve
    - torch-model-archiver
    - torch-workflow-archiver
    - nvgpu
    - optimum
    - psutil==5.9.5
    - requests
    - captum==0.6.0
    - packaging
    - pynvml
    - pyyaml
    - ninja
    - grpcio
    - protobuf
    - grpcio-tools
    - googleapis-common-protos
    - flask
    - flask-restful
    - ninja
    - torch-ort
    - elasticsearch
    - onnxruntime-gpu
    - openai
    - ollama
    - langchain
    - langchain-community
    - langchain-huggingface
    - langchain-elasticsearch
    - langchain-openai
    - langchain-ollama
    - langserve[all]
    - langchain-cli
    - pybind11
    - git+https://github.com/NVIDIA/TensorRT-LLM.git    
    
