name: base
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch::faiss-gpu
  # github runner doesn't have a gpu, it seems not working , disable for now. 
  # might work using https://github.com/gpgpu-sim/gpgpu-sim_distribution, check it later
  # - nvidia/label/cuda-11.8.0::cutatoolkit
  - pandas=2.0.3
  - pip
  - numpy=1.24.3
  - openpyxl=3.0.10
  - scipy=1.10.1
  - sqlalchemy=2.0.21
  - ipywidgets
  - ipympl
  - cython=0.29
  - statsmodels=0.14.0
  - jupyterlab
  - numba=0.58.1
  - numexpr=2.8.4
  - xlrd=2.0.1
  - conda-forge::imbalanced-learn=0.11.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::spacy=3.5.4
  - anaconda::unqlite
  - pip:
    - setuptools==65
    - git+https://github.com/medspacy/medspacy_io.git
    - medspacy==1.1.5
    - scikit-spark
    - nltk==3.8.1
    - bioc==2.0
    - tqdm==4.65
    - tensorboard
    - pytest
    - wheel
    - joblib
    - matplotlib
    - xgboost
    - pyspark==3.5.0
    - spark-nlp==5.2.0
    - mlflow
    - gensim
    - Keras
    - pydot
    - graphviz
    # - tensorflow==2.12.0 # only need this for Visual NLP
    - PyRuSH>=1.0.8
    - pysbd==0.3.4
    - jsonschema
