name: base
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.8
  # - nvidia/label/cuda-11.4.1::cuda-toolkit     # split the cudatoolkit installation to different layer
  # - conda-forge:cudnn=8.1.0
  - pytorch::faiss-gpu
  # github runner doesn't have a gpu, it seems not working , disable for now. 
  # might work using https://github.com/gpgpu-sim/gpgpu-sim_distribution, check it later
  # - nvidia/label/cuda-11.8.0::cutatoolkit
  - pandas=2.0.3
  - pip
  - numpy=1.24.3
  - openpyxl=3.0.10
  - scipy=1.10.1
  - sqlalchemy=2.0.21
  - ipywidgets
  - ipympl
  - cython=0.29
  - statsmodels=0.14.0
  - notebook
  - jupyterlab
  - numba=0.58.1
  - numexpr=2.8.4
  - xlrd=2.0.1
  - conda-forge::torchinfo=1.8.0
  - conda-forge::imbalanced-learn=0.11.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::jupytext
  - conda-forge::spacy=3.5.4
  - conda-forge::pyarrow=14.0.1
  - pip:
    - setuptools==65
    - medspacy
    - git+https://github.com/medspacy/medspacy_io.git
    - nltk==3.8.1
    - bioc==2.0
    - tqdm==4.65
    - tensorboard
    - pytest
    - wheel
    - joblib
    - matplotlib
    - pyspark==3.5.0
    - spark-nlp==5.2.3
    - mlflow
    - gensim
    - Keras
    - scikit-spark
    - pydot
    - graphviz
