name: win_dspy
channels:
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - conda-forge:cudnn
  - pytorch::torchtext
  - pandas=2.0.3
  - pip
  - numpy=1.24.3
  - openpyxl=3.0.10
  - sqlalchemy=2.0.21
  - ipympl
  - cython=0.29
  - loguru
  - jupyterlab
  - xlrd=2.0.1
  - conda-forge::torchinfo=1.8.0
  - conda-forge::imbalanced-learn=0.11.0
  - conda-forge::scikit-learn=1.3.2
  - conda-forge::jupytext
  - pip:
    # https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/layers
    # may consider torchdynamo in later versions
    # https://pytorch.org/docs/stable/dynamo/installation.html
    - setuptools==65
    - spacy
    - transformers
    - simpletransformers
    - nltk==3.8.1
    - bioc==2.0
    - tqdm
    - tensorboard
    - pytest
    - wheel
    - joblib
    - itsdangerous<2.1.0
    - accelerate
    - pyspark==3.5.1
    - spark-nlp==5.2.3    
    - dspy-ai==2.4.0
    - datasets

