name: tvm-build

# The conda channels to lookup the dependencies
channels:
  - conda-forge
  - anaconda

# The packages to install to the environment
dependencies:
  - python=3.8 # or 3.8. See https://github.com/apache/tvm/issues/8577 for more details on >= 3.9
