name: build_push_large
# this workflow added maximize-build-space action to get larger disc to build.
run-name: B&D ${{ github.event.inputs.hub_username }}/${{ github.event.inputs.build_folder }}:${{ github.event.inputs.tag }}  
on:
  workflow_dispatch:
    inputs:
      build_folder:
        description: 'From which folder, the Dockerfiles will be built'  
        type: string   
        required: false
        default: 'cosmos_base'
      tag:
          description: 'Customize image tag'  
          type: string   
          required: false
          default: 'latest'
      hub_username:
        description: 'Docker hub username'  
        type: string   
        required: false
        default: 'brokenjade'

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'          
          remove-dotnet: 'true'

      - name: check docker containers
        run: |
          sudo docker container ls -a
      
      - name: Set docker storage to lvm
        continue-on-error: true
        run: |
          sudo docker images
          sudo docker rmi node:16
          sudo docker rmi node:18
          sudo docker rmi debian:10
          sudo docker rmi ubuntu:20.04
          # https://tienbm90.medium.com/how-to-change-docker-root-data-directory-89a39be1a70b
          sudo systemctl stop docker
          echo "try restart and restop..."
          sudo systemctl start docker
          sudo systemctl status docker.service
          sudo systemctl stop docker
          sudo systemctl status docker.service
          echo "{\"data-root\": \"/home/runner/work/docker\"}"  | sudo tee -a /etc/docker/daemon.json 
          echo "copy existing files..."
          sudo rsync -aPq /var/lib/docker/ /home/runner/work/docker
          # sudo rm -rf /var/lib/docker
          sudo ls -l /home/runner/work/docker
          echo "restart docker..."
          sudo df -h
          sudo modprobe -r overlay && modprobe overlay redirect_dir=on
          sudo systemctl start docker
      
      - name: check error
        continue-on-error: true
        run: |
          sudo systemctl status docker.service
          
      - name: check error2
        continue-on-error: true
        run: |
          sudo docker info

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.event.inputs.build_folder  }}
          restore-keys: |
            buildx-${{ github.event.inputs.build_folder  }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.event.inputs.hub_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          pwd
          ls
          cd ${{ github.event.inputs.build_folder }}
          docker build -t ${{ github.event.inputs.hub_username }}/${{ github.event.inputs.build_folder }}:${{ github.event.inputs.tag }} .
          
      - name: list images
        run: docker images

      - name: publish
        run: |
          docker image push ${{ github.event.inputs.hub_username }}/${{ github.event.inputs.build_folder }}:${{ github.event.inputs.tag }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ github.event.inputs.hub_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.event.inputs.hub_username }}/${{ github.event.inputs.build_folder }}
          readme-filepath: "${{ github.event.inputs.build_folder }}/README.MD"

      # only works if built on self-hosted runners. Github runners do not have enough space for this.

      # - name: Save image as a tar for later use 💾
      #   run: docker save ${{ github.event.inputs.hub_username }}/${{ github.event.inputs.build_folder }}:${{ github.event.inputs.tag }} -o /tmp/${{ github.event.inputs.hub_username }}-${{ github.event.inputs.build_folder }}.tar
      #   shell: bash
      # - name: Upload image as artifact 💾
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ github.event.inputs.hub_username }}-${{ github.event.inputs.build_folder }}
      #     path: /tmp/${{ github.event.inputs.hub_username }}-${{ github.event.inputs.build_folder }}.tar
      #     retention-days: 3
