name: build_win_env
run-name: B&D ${{ github.event.inputs.build_folder }}
on:
  workflow_dispatch:
    inputs:
      build_folder:
        description: 'From which folder, the conda environment will be built'  
        type: string   
        required: false
        default: 'win_cuda'
      target_folder:
        description: 'target folder path (must be on D drive)'
        type: string
        required: false
        default: 'D:/conda_envs/mine/'

permissions:
  actions: write
  contents: read
        
jobs:
  create_env:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Check Setting Folder
      run: |
        pwd
        ls ${{ github.event.inputs.build_folder }}
    
    - name: Cache Miniforge Environment
      uses: actions/cache@v2
      with:
        path: ${{ github.event.inputs.target_folder }}
        key: ${{ runner.os }}-conda-${{ hashFiles('${{ github.event.inputs.build_folder }}/environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-

    - name: Install miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        miniforge-version: latest
    
    - name: Create Conda Environment
      run: |
        cd ${{ github.event.inputs.build_folder }}
        conda env create -f environment.yml -p ${{ github.event.inputs.target_folder }}

    - name: check folder
      run: |
        ls ${{ github.event.inputs.target_folder }}
        
    - name: Check for 7-Zip installation
      run: |
        if (!(Test-Path "C:\Program Files\7-Zip\7z.exe")) {
          choco install 7zip
        }
  
    - name: Compress and split folder
      run: |
        pwd
        7z a -t7z -v10m ${{ github.event.inputs.build_folder }}.7z ${{ github.event.inputs.target_folder }}*
        ls

    - name: Upload each volume as an artifact
      shell: pwsh
      run: |
        $headers = @{
          "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
          "Accept" = "application/vnd.github.v3+json"
        }
        $repoName = "${{ github.repository }}"
        $runId = "${{ github.run_id }}"

        ls *.7z*

        # Find all the 7z files
        $files = Get-ChildItem -Path . -Filter "${{ github.event.inputs.build_folder }}.7z.*"

        foreach ($file in $files) {
          $artifactName = $file.Name
          $uploadUrl = "https://api.github.com/repos/$repoName/actions/runs/$runId/artifacts"
          

          # Create an artifact
          $body = @{
            name = $artifactName
            expires_at = (Get-Date).AddDays(1).ToString("o") # Set expiration to 1 day from now
          } | ConvertTo-Json

          $response = Invoke-RestMethod -Uri $uploadUrl -Method Post -Headers $headers -Body $body
          $uploadArtifactUrl = $response.upload_url

          # Upload the artifact file
          Invoke-RestMethod -Uri $uploadArtifactUrl -Method Post -Headers $headers -ContentType "application/zip" -InFile $file.FullName
        }
