name: del_artifacts

on:
  workflow_dispatch:

jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Delete all artifacts
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { repo } = context;
          // No need to getOctokit, directly use the github object provided
          const listArtifacts = await github.rest.actions.listArtifactsForRepo({
            owner: repo.owner,
            repo: repo.repo,
          });
          const artifactIds = listArtifacts.data.artifacts.map(artifact => artifact.id);
          
          for (const artifactId of artifactIds) {
            await github.rest.actions.deleteArtifact({
              owner: repo.owner,
              repo: repo.repo,
              artifact_id: artifactId,
            });
            console.log(`Deleted artifact ${artifactId}`);
          }