name: del_artifacts

on:
  workflow_dispatch:

jobs:
  cleanup-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Delete all artifacts
      uses: actions/github-script@v6
      with:
        script: |
          const octokit = github.getOctokit(core.getInput('token'));
          const { owner, repo } = context.repo;
          const listArtifacts = await octokit.rest.actions.listArtifactsForRepo({
            owner,
            repo,
          });
          const artifactIds = listArtifacts.data.artifacts.map(artifact => artifact.id);
          
          for (const artifactId of artifactIds) {
            await octokit.rest.actions.deleteArtifact({
              owner,
              repo,
              artifact_id: artifactId,
            });
            console.log(`Deleted artifact ${artifactId}`);
          }
        token: ${{ secrets.GITHUB_TOKEN }}