name: test_run

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image name to run'  
        type: string   
        required: false
        default: 'brokenjade/helloworld'
      cmd:
          description: 'command to run after docker run'  
          type: string   
          required: false
          default: 'echo "ok"'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: test run
        run:
          docker run ${{ github.event.inputs.image_name }}  ${{ github.event.inputs.bash }} 