name: Upload Each File as Artifact

on: [push]

jobs:
  upload-artifacts:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate files
      run: |
        mkdir files
        # Example: Generate 5 text files. Adjust this script to generate your files.
        $filesPath = "files"
        1..5 | ForEach-Object {
          $filename = "${filesPath}\File$_.txt"
          "Hello, this is file $_" | Out-File $filename
        }

    - name: Upload files as individual artifacts
      shell: pwsh
      run: |
        $files = Get-ChildItem ./files -File
        foreach ($file in $files) {
          $zipName = "$($file.BaseName).zip"
          Compress-Archive -Path $file.FullName -DestinationPath $zipName
          echo "Uploading $zipName as an artifact"
          # Now upload the zipped file as an artifact
          - name: Upload F
            uses: actions/upload-artifact@v4
            with:
              name: $file.BaseName
              path: $zipName
        }
