name: test_max_docker
# test configure maximize-build-space action for docker build
on:
  workflow_dispatch

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Backup docker files
        run: |
          echo "backup moby/buildkit image"
          sudo docker image save -o /mnt/images.tar moby/buildkit
          sudo find /var/lib/docker/. -maxdepth 5 -type d > ${GITHUB_WORKSPACE}/dirs.txt
          sudo cat ${GITHUB_WORKSPACE}/dirs.txt


      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'          
          remove-dotnet: 'true'
          # instead of using default value to mount to build path, /var/lib/docker/ is really the place we need more spaces.
          build-mount-path: '/var/lib/docker/'

      - name: Restore docker files
        run: |
          sudo ls /var/lib/docker -l
          sudo pwd
          sudo ls /mnt -l
          sudo xargs mkdir -p < ${GITHUB_WORKSPACE}/dirs.txt
          sudo docker image load -i /mnt/images.tar
          sudo rm /mnt/images.tar

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3      
              
      - name: list images
        run: docker images

      - name: check storage
        run: |
          sudo df -h
          ls /tmp -l

    