name: test_jdk_install

on:
  workflow_dispatch:
    inputs:
      jdk_version:
        description: 'an integer of jdk version'  
        type: string   
        required: false
        default: '8'

jobs:
  run_docker:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  
          
      - name: install jdk
        run: |
          pip install install-jdk
          python -c "import jdk; jdk.install('${{ github.event.inputs.jdk_version }}');"
      

      - name: test jdk
        run: |
          java --version
          which java