name: test_run

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image name to run'  
        type: string   
        required: false
        default: 'jupyter/pyspark-notebook'
      cmd:
          description: 'command to run after docker run'  
          type: string   
          required: false
          default: 'echo "ok"'

jobs:
  run_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-${{ github.event.inputs.image_name }}
          restore-keys: |
            ${{ runner.os }}-${{ github.event.inputs.image_name }}

      - name: Set up Docker env
        uses: docker/setup-buildx-action@v2.5.0

      - name: test run
        run:
          docker run --entrypoint=${{ github.event.inputs.cmd }}  ${{ github.event.inputs.image_name }}  