name: test_multi_artifacts
on:
  workflow_dispatch


jobs:
  upload-multiple-artifacts:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        # Setup your environment as necessary
        mkdir files
        # Example: Generate files dynamically. Adjust this as needed.
        echo "Generating files..."
        1..5 | ForEach-Object { Out-File -FilePath "files/File$_.txt" -InputObject "Content for file $_" }


    - name: Upload each volume as an artifact
      shell: pwsh
      run: |
        $files = Get-ChildItem -Path files
        foreach ($file in $files) {
          echl $file
          gh workflow run upload-artifact.yml --repo ${{ github.repository }} -f artifact-name=$file.Name -f artifact-path=$file.FullName
        }