name: Upload Each File as Zipped Artifact

on: [push]

jobs:
  upload-artifacts:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate files
      run: |
        mkdir files
        # Example: Generate 5 text files. Adjust this script to generate your files.
        1..5 | ForEach-Object {
          $filename = "files\File$_.txt"
          "Hello, this is file $_" | Out-File $filename
        }

    - name: Zip and Upload files as individual artifacts
      run: |
        $files = Get-ChildItem ./files -File
        foreach ($file in $files) {
          $zipName = "$($file.BaseName).zip"
          Compress-Archive -Path $file.FullName -DestinationPath $zipName
          echo "Uploading $zipName as an artifact..."
          $artifactName = $file.BaseName
          # Use actions/upload-artifact to upload the zipped file
          echo "::set-output name=$artifactName::$zipName"
        }
      shell: pwsh
