name: Upload Multiple Artifacts

on: [push]

permissions:
  actions: write
  contents: read

jobs:
  upload-multiple-artifacts:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        # Setup your environment as necessary
        mkdir files
        # Example: Generate files dynamically. Adjust this as needed.
        echo "Generating files..."
        1..5 | ForEach-Object { Out-File -FilePath "files/File$_.txt" -InputObject "Content for file $_" }

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run upload script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python upload_artifacts.py "./files" --expire_days 10
